pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage ('Deploy in Staging environment'){
            steps {
                build job: 'DeployApplicationStagingEnv'
            }
        }
        stage ('Deploy in Production'){
            steps {
                timeout(time:5, units:'DAYS'){
                    input message: 'Approve PRODUCTION DEPLOYMENT'
                }
                build job: 'DeployApplicationProdEnv'
            }
        }
    }
}